### ISSUE TITLE
Plan for future?

### ISSUE THREAD

**Issue by ibizaman** [Xide/t411cli#1]
Hi,

I just wanted to let you know this is awesome. And I'm using it right now.
I also wanted to know where do you want to go with this?

EDIT: I made a little wrapper around your tool to make the workflow more enjoyable, at least for me. https://gist.github.com/267a926b502d7a4f8fa4

**Comment by Xide** [comment]
Hey, thanks you, glad you like it !
We will change majors things in the future, starting with the possibility to plug in with any torrent API.
We also want to add a curses interface as we find CLI usage unpractical in some situations, and i see with your wrapper that you too ;)
Thanks for your work BTW, can I put a link to this in the readme of the project until the curse functionality is operational ?

**Comment by ibizaman** [comment]
Of course, just copy paste it in the readme. Btw, I'm so glad you're thinking of a curses interface.
